### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by leeyunhome** [mikel-brostrom/Yolov5_DeepSort_Pytorch#102]
Hello,

thanks for the good material
I ran into the following problem while running track.py.

Is the path to run track.py under Yolov5_DeepSort_Pytorch correct?

(yolov5_ds) D:\coding\GitHub\Yolov5_DeepSort_Pytorch>python track.py --source "Pexels Videos 2073129.mp4"
Traceback (most recent call last):
  File "track.py", line 4, in <module>
    from yolov5.models.experimental import attempt_load
  File "D:\coding\GitHub\Yolov5_DeepSort_Pytorch\yolov5\models\experimental.py", line 7, in <module>
    from models.common import Conv, DWConv
  File "D:\coding\GitHub\Yolov5_DeepSort_Pytorch\./yolov5\models\common.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

What am I supposed to do?

Thank you.

**Comment by mikel-brostrom** [comment]
Given that your run fails on the first yolov5 import I would say that you haven't initialized the repository correctly.
Instead of running:

`git clone https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`

you have to run

`git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`

**Comment by mikel-brostrom** [comment]
If that is not working you could try to: `pip install requests`

**Comment by mikel-brostrom** [comment]
Try: 

`pip install requests`
