### ISSUE TITLE
Multi Camera Multi Object tracking 

### ISSUE THREAD

**Issue by sainivedh** [mikel-brostrom/Yolov5_DeepSort_Pytorch#103]
Any idea on How to move forward with Multi Camera Multi Object tracking ?. 

Like if the same person goes from cam1 to cam2 model should recognize him as the same person. Any advice/tip would be much appreciated.

Thanks

_Originally posted by @sainivedh in https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/88#issuecomment-862232332_

**Comment by mikel-brostrom** [comment]
I think that a good way of doing this is to:

1. Create a DeepSort class for each camera stream
2. Share the tracks among the DeepSort classes, but only id and feature vector (will let you re-identify the object by its visual features). This is because the state space is probably of no use as the cameras could be positioned in such way that the movement drastically changes in image space when a certain object go from camera1 to camera2.
3. Set track's max age to a large number (as you don't know how many frames it will take for a certain object to go from camera1 to camera2)

Feel free to post your results here @sainivedh, it would be interesting to see you results.

**Comment by abhi0928** [comment]
@mikel-brostrom can we create multiple instances of deepsort track.py and call them using multiprocessing?

**Comment by mertcihangiroglu** [comment]
> Any idea on How to move forward with Multi Camera Multi Object tracking ?.
> 
> Like if the same person goes from cam1 to cam2 model should recognize him as the same person. Any advice/tip would be much appreciated.
> 
> Thanks
> 
> _Originally posted by @sainivedh in [#88 (comment)](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/88#issuecomment-862232332)_

I advise you to look at Torch Reid Framework for this task. It is quite complicated task to achive than normal detection. Here some links might be helpful: 

https://asp-eurasipjournals.springeropen.com/track/pdf/10.1186/s13634-017-0482-z.pdf

https://github.com/samihormi/Multi-Camera-Person-Tracking-and-Re-Identification

https://github.com/lyrgwlr/Human-tracking-multicam

**Comment by jyothirrose** [comment]
any solution for multi camera tracking?
