### ISSUE TITLE
evaluate different datasets in'' yolov5_deepsort _pytorch''  track level

### ISSUE THREAD

**Issue by tangchenhuan** [mikel-brostrom/Yolov5_DeepSort_Pytorch#113]
can you show the evaluate track code  in your project?

**Comment by tangchenhuan** [comment]
i think you are take the evaluate code in your project,and take the word to say how to evaluate different datsets track level ,not just eval.sh file.

**Comment by mikel-brostrom** [comment]
I make use of the (official MOT16 evaluation repo)[https://github.com/JonathonLuiten/TrackEval]  in order to perform the evaluation. I have no intention to change this. 

Check that repo if you want to know more about how the different tracking evaluation metrics are calculated. You can also adapt eval.sh to perform the evaluation on a different dataset.
