### ISSUE TITLE
DeepSort bbox is large

### ISSUE THREAD

**Issue by songtf525** [mikel-brostrom/Yolov5_DeepSort_Pytorch#131]
Thank you for your rep.
    When I use yolov5 as the detector, the bounding box can fit the vehicle well when the vehicle appears at the bottom of the image, but after adding deepsort tracking, the position of the frame that comes out will become very large at first, and then slowly fit the vehicle. Where is this set up?

**Comment by songtf525** [comment]
This question is not clearly expressed as my problem. 
For tracking and detection, the position of the bbox given by the tracking is not accurate and stable, so does deepsort have to give a detection result by itself? How can this be improved?

**Comment by mikel-brostrom** [comment]
We are plotting the propagated state distribution to the current time step, not the Yolov5 bounding boxes themselves. This means that in the early stages of the KalmanFilter the estimations could potentially be bad as new observations (Yolov5 detections) could be poor. This gets corrected with more measurement as the filter cyclically overrides the mean and variance for the track's state. This is why sometimes you get larger bounding boxes for objects that just got into the filed of view of the camera, because the track's state is making drastic updates to its distribution based on new observations (Yolov5 detection)

**Comment by mikel-brostrom** [comment]
The better the observations, the better the estimations. Specially in the early stages of a track's life. If you choose a larger Yolov5 model, for example Yolov5x, you will probably see a stabler tracking performance
