### ISSUE TITLE
Can't find .mp4 video file in inference/output

### ISSUE THREAD

**Issue by xiaofeng-c** [mikel-brostrom/Yolov5_DeepSort_Pytorch#140]
Hello,thanks for your work,i run the track.py with my .mp4 video file as inputting file,but when the process end,i can't find my output .mp4 file,do you know what wrong with it?

**Comment by mikel-brostrom** [comment]
The CI pipeline is passing which means that everything should work "out of the box" simply by calling `track.py` with the flags of your choice. Try to start from a clean slate. Re-clone so that you can be sure that you get the latest updates (automatic weight downloads among others) and then try something like

```
python3 track.py --source 0 --show-vid
```

**Comment by mikel-brostrom** [comment]
Cannot be sure what is going on as you don't specify which command you run the tracker with.
But most certainly you only forgot to enable the saving flag:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/461c80ce7aa5a7901f722d072a955ec4909dcfcc/track.py#L212

Try the following command:

```
python3 track.py --source 0 --save-vid
```

**Comment by xiaofeng-c** [comment]
Thank you very much!
