### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'

### ISSUE THREAD

**Issue by besbesmany** [mikel-brostrom/Yolov5_DeepSort_Pytorch#142]
I got this error how to get chpt.t7??

**Comment by mikel-brostrom** [comment]
The CI pipeline is passing which means that everything should work "out of the box" simply by calling track.py with the flags of your choice. Try to start from a clean slate. Re-clone so that you can be sure that you get the latest updates (automatic weight downloads among others) and then try something like

```
python3 track.py --source 0 --show-vid

```

**Comment by besbesmany** [comment]
thank you sir

**Comment by TheDirection** [comment]
You should download it from google drive through a website by yourself.

**Comment by mikel-brostrom** [comment]
> You should download it from google drive through a website by yourself.

This is not the case anymore. The weights are now downloaded automatically, both Yolov5 and DeepSort
