### ISSUE TITLE
missing results of a frame in output file

### ISSUE THREAD

**Issue by hhoanguet** [mikel-brostrom/Yolov5_DeepSort_Pytorch#144]
When I add --save-txt flag to get MOT compliant results, the output txt file does not contain results of frame 1 in my inference video. Although, the model detects 9 persons in frame 1 as i see in the output log when running track.py

**Comment by mikel-brostrom** [comment]
That is because of:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/9935d81231192f6a977954c4ff5d8361071ee6cf/deep_sort_pytorch/deep_sort/sort/track.py#L33

Each track needs to be found `n_init` amount of times before it is confirmed and the bbox associated to them shows in the video.
The parameter is defined here:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/461c80ce7aa5a7901f722d072a955ec4909dcfcc/deep_sort_pytorch/configs/deep_sort.yaml#L8
