### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by ChunmianLin** [mikel-brostrom/Yolov5_DeepSort_Pytorch#15]
Hi, author. Thanks a lot for your great work.
But I think the environment is too new to apply to local user. Could you please low down the environment setting, i.e. torch=1.3 or 1.4, NVIDIA Driver>=410, etc.
Thanks again for your help.

**Comment by mikel-brostrom** [comment]
Hi @ChunmianLin 
Thank you!

I am sorry to tell you that what you ask for is not possible. This is because Yolov5_DeepSort_Pytorch mostly contains the work of other people which makes my code constrained to their requirements.

You are welcome to use https://github.com/mikel-brostrom/Yolov3_DeepSort_Pytorch, as it seems to fulfill your environment settings, if that is of any help

**Comment by ChunmianLin** [comment]
@mikel-brostrom Thanks again for your reply. I would consider for your recommendation, but I also want to apply the YOLOv5 tracker to my research. It is so dilemma.
