### ISSUE TITLE
Kalman Filtering Modification

### ISSUE THREAD

**Issue by YasserJaber98** [mikel-brostrom/Yolov5_DeepSort_Pytorch#214]
I have been struggling with understanding the code of Kalman Filtering.
How can I modify the code such that it can work and predict state of fast-moving objects?

I would appreciate any help :)

**Comment by mikel-brostrom** [comment]
The Kalman Filter is already predicting states for each track... What do you mean?

**Comment by mikel-brostrom** [comment]
Do you experience association losses for fast traveling objects? 

My guess is that the KF loses track of the object since the observations lie outside of the association zone around the predicted state of the KF. This is most certainly a result of not being able to keep up with the object's sudden change in velocity  (as the initial mean velocity is 0).

You can try to make the association zone larger by increasing the Mahalanobis gating threshold here:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/5336c022a72ef7456bc94a37f6c29836cad1bebc/deep_sort_pytorch/deep_sort/sort/tracker.py#L36

You can also try to hardcode a larger initial velocity.
