### ISSUE TITLE
An error occurred using my own training yolov5x.pt

### ISSUE THREAD

**Issue by ddg238** [mikel-brostrom/Yolov5_DeepSort_Pytorch#216]
I trained a model to detect table tennis, and I want to use this code to track, but an error occurs when it runs
error：
![issues](https://user-images.githubusercontent.com/85625085/140880289-2dce6a8f-1fb9-4fc7-9c17-52b71f1780a1.png)
I know my question may be repeated but #212  does not give a detailed solution

**Comment by arvidle** [comment]
This seems to be caused by changes in the yolov5 repo, which are not yet implemented here. This is probably why the submodule of yolov5 is still pinned to an older commit.
I was able to work around the exact same error by using the version of yolov5 the submodule is pinned to to train my custom net.

The easiest way to do this is to just use the yolov5 cloned as a submodule by this repository to train your custom network.
Otherwise, you can checkout the branch of yolov5 referenced by this repository in the yolov5 clone you use for training (at the moment `git checkout aa18599`).

While this is not a long-term fix, this should make everything work as intended.

**Comment by mikel-brostrom** [comment]
The yolov5 submodule is now updated.
You should be able to load your weights.
Pull and try again.
Let me know whether this works for you or not.

**Comment by arvidle** [comment]
I tested the tracking with a model trained on the most recent version of yolov5 and everything works as intended.
