### ISSUE TITLE
New track ID creation

### ISSUE THREAD

**Issue by sriktrako** [mikel-brostrom/Yolov5_DeepSort_Pytorch#230]
Hi @mikel-brostrom thanks for sharing your awesome work.

I am testing on a fisheye view camera(placed at center of room) with custom yolo weights to detect heads. I am facing track drop issue in the following two scenarios:
1. Track is dropping and changing quickly from eg: 5 to 15 when person walks slightly faster
2. Since I am testing on fisheye view, eg: when the person is in a corner of the room the majority of detection box contains the frontal face, as the person keeps walking towards center of the room the detection box contains the top of the head as he is standing under the camera and when he walks away the detection box contains back of the head. For these three cases 3 separate track ID's are being created and the track id is changing across the 3 track id's depending on where the person is in the room. How to tackle the perspective change challenge?         
I tried tuning the parameters, but didn't make much progress. Do you have any advice on this? 
Thank you for your help in advance!

**Comment by mikel-brostrom** [comment]
This is a know issue. For fixed camera positions it can be due to, in part, to the fact that the Mahalanobis distance is only used to gate the cosine distances and not in a weighted sum as described here: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/138. Hence, the predictable movements is not used in its full extent to get better id matchings. Feel free to leave a PR!

**Comment by sriktrako** [comment]
Okay I will try this and see if there's any improvement, Thanks.
