### ISSUE TITLE
result

### ISSUE THREAD

**Issue by fengshuaibo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#259]
The result of your project is to reduce IDS switching compared to other methods, right? What is your effective method to reduce IDS in this project

**Comment by mikel-brostrom** [comment]
Yes, Deep sort is known for its low IDS.

A lot has happened to both object detection and ReID models since the release of the DeepSort paper. The idea of this repo was to build a workbench of automatically downloade-able SOTA models for both stages of the tracker in order to push the DeepSort approach.

> What is your effective method to reduce IDS in this project

In general, the larger the models the better the object detection and ReID performance and hence lower IDS. Then there is some hyperparameter tuning to do for DeepSort to maximize the tracker's performance
