### ISSUE TITLE
Reduce detection fps but keep tracking between all frames

### ISSUE THREAD

**Issue by Kiwa21** [mikel-brostrom/Yolov5_DeepSort_Pytorch#260]
Hello,
Thanks for this project, it's very helpful to start playing with Yolo and Deepsort.
If I'm not wrong, currently all frames are processed by yolo and deepsort.
Is is possible to drop the framerate of the detector (since it's the most consuming) and only detect maybe at 5-10fps but run the deepsort tracker on all frames ?
The idea is also to have an output video with all frames of course.

Do you have way of doing that ? or an hint for me to try ?

Thanks,

**Comment by mikel-brostrom** [comment]
Correct me if I am wrong.

You want to make multiple KF predictions ahead. The same amount of predictions ahead as the number of frames you skip? And then make the association.

Why not pick a smaller Yolov5 model such as the Yolov5n? Isn't that fast enough for your needs?

**Comment by Kiwa21** [comment]
Yes that's right.
I need to detect small features in HD / large image so I need to run the  yolov5 with the highest image size possible. Of course, even using a good GPU, I cannot maintain 30 fps computing speed.
What I've done as a workaround is to run detection on 1 every 4 frames, and use the output to draw the same bboxes on the next 3 frames.
It makes the stream a bit sloppy if the camera or the target moves fast, and rather than considering the dectictions statics, I would like the KF to predict the bboxes position for next 3 frames.

I tried to use the predict() fonction of the tracker without the update or increment ages but i'm not sure how to use it for now..

**Comment by Kiwa21** [comment]
Final goal is to keep the bbox as long as possible and smooth the display (less shaking around bboxes as well).

**Comment by mikel-brostrom** [comment]
In my opinion, the natural thing to do here would be a prediction ahead

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/7eb169e6a1810f6067076ab41083e916b864ed12/deep_sort/deep_sort.py#L37

then take the bbox of each track 

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/7eb169e6a1810f6067076ab41083e916b864ed12/deep_sort/sort/track.py#L100

and finally feed them to the update of the tracker 

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/7eb169e6a1810f6067076ab41083e916b864ed12/deep_sort/deep_sort.py#L38

 instead of the observation from yolo on those 3 frames. Feed the yolo prediction on the 4th so that the state of the KF gets up to date with the latest observation.

**Comment by XiangqingZhang** [comment]
@Kiwa21 
Have you solved the problem ?  how to run detection on 1 every 4 frames, and use the output to draw the same bboxes on the next 3 frames.
