### ISSUE TITLE
运行出错！！！

### ISSUE THREAD

**Issue by gubei528** [mikel-brostrom/Yolov5_DeepSort_Pytorch#272]
File "D:\Anaconda\Anaconda\envs\deepsort\lib\site-packages\torch\nn\functional.py", line 2111, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])
为什么我跑视频的时候会报这个错误呢？有的视频就没有，而且还有的时候有这个错误，有的时候 没有！请问有人遇到过吗？该怎么解决！

**Comment by ggarrett13** [comment]
@gubei528 It looks like you're passing a grayscale video/image into a model designed for and/or pretrained on 3 channel input (R,G,B) instead of grayscale. [Here's a post with some solutions.](https://stackoverflow.com/questions/51995977/how-can-i-use-a-pre-trained-neural-network-with-grayscale-images)

**Comment by mikel-brostrom** [comment]
The way of doing this with opencv is

`rgb_img = cv2.cvtColor(gray_scale_img, cv2.COLOR_GRAY2RGB)`
