### ISSUE TITLE
DeepSort implementation: Actual state

### ISSUE THREAD

**Issue by Camilochiang** [mikel-brostrom/Yolov5_DeepSort_Pytorch#341]
Good day. 
Your implementation is using now (I think that previously didnt) ReID models. For the same it fail  when using other classes (not 100%, but still is not so good).
 Are you planning to allow other tracking models for non humans objects?  I think that will be helpful to mentioned in the readme.md that your implementation is using a deep sort model trained to follow mainly humans (full body humans)

**Comment by mikel-brostrom** [comment]
Previously it also used ReID models. ALL of them are trained on people. Mainly because there are no other publicly available ReID datasets with other classes.

**Comment by youonlytrackonce** [comment]
Does you project still work with reid model "ckpt.t7"?

**Comment by mikel-brostrom** [comment]
Not the newer releases. The reason is the decrease in performance when using "ckpt.t7"

**Comment by youonlytrackonce** [comment]
hmm, I was working with that model and then trained a new yolov5 model. New yolov5 model does not work in your old project which uses ckpt.t7 and your latest version does not support ckpt.t7 anymore. Is it possible for you to add this option as a deepsort model? Otherwise I need to add manually to my project and then diverge from your repo.

Thank you.
