### ISSUE TITLE
Problem: tracking lost, tracking id exchange

### ISSUE THREAD

**Issue by eeric** [mikel-brostrom/Yolov5_DeepSort_Pytorch#39]
The algorithm needs to be improved.

**Comment by eeric** [comment]
please author take a time to  answer.

**Comment by mikel-brostrom** [comment]
To answer to what? Your first comment is not even a question.
By all the issues that you opened I can see that you misunderstood the concept of open source. 

Be respectful and spend some time writing proper questions so that I don't have to loose my time writing
answers like his, time is money and I don't get paid for this. If you open an issue you can at least suggest some kind of idea to solve a specific problem, if you are unable to resolve it yourself, explain that. This is not a buffet type of place where you get
whatever you want, this is a collaborative space and I don't see you contributing with anything more
than: "tracking is not accurate", "re-id not okay", "algorithm needs to be improved" and that I need to answer to non-existing questions
