### ISSUE TITLE
How to get the matched detections and not the tracks?

### ISSUE THREAD

**Issue by iAmJuan550** [mikel-brostrom/Yolov5_DeepSort_Pytorch#72]
In your code, you match your track with the detection and then you return the track bounding box instead of the detection bounding box with which the tracked bounding box matched. How do I instead get the detection bounding box?

**Comment by Dishant-P** [comment]
Well, if at all you do that, it will be basically bypassing DeepSort. Because once you use update() function, you are giving the detections to DeepSort and then using that bounding boxes. 
If at all you want that you can simple skip tracker.update() and directly use the det for drawing bounding boxes.

**Comment by iAmJuan550** [comment]
I solved this problem by using the original deep sort repository and not this one.

**Comment by lucy3589** [comment]
> I solved this problem by using the original deep sort repository and not this one.

Could you give me original deepsort url?  I search for paper url----use tracker bbox.

**Comment by diazGT94** [comment]
Hey @iAmJuan550 Are you using the original DeepSort repo with YoloV5?
