### ISSUE TITLE
The latest pull had a problem with not displaying video

### ISSUE THREAD

**Issue by CynicalHeart** [mikel-brostrom/Yolov5_DeepSort_Pytorch#97]
In code ：
```python
parser.add_argument('--view-vid', action='store_false',  help='display results')  
```
I directly ignored this parameter because it is store_false. But the result is the following👇

![image](https://user-images.githubusercontent.com/27052882/117937357-78bb1880-b338-11eb-8870-f0bb7bc734ed.png)

In the function check_imshow( ), it incorrectly checks my system. Why?

**Comment by CynicalHeart** [comment]
This is a very coincidental bug：
```python
# yolov5/utils/general.py 54 line
def is_docker():
    # Is environment a Docker container
    return Path('/workspace').exists()  # or Path('/.dockerenv').exists()

>>>Path('/workspace').exists()
True
>>>Path('/dockerenv').exists()
False
```
I have a path like this --- `D:\workspace\MTMC` , is that the reason?

**Comment by mikel-brostrom** [comment]
I don't know which docker images you are running this on but it looks like you need to allow the docker container to access your local XServer. This would show all graphical output as if you ran the software directly on the host instead of in a Docker container. In order to do this, you need to set the DISPLAY environment variable and you need to pass the X11 socket to the container.

**Comment by mikel-brostrom** [comment]
This may help you: https://stackoverflow.com/questions/36798277/run-opencv-in-jupyter-with-docker

**Comment by CynicalHeart** [comment]
> This may help you: https://stackoverflow.com/questions/36798277/run-opencv-in-jupyter-with-docker

Thanks.
