### ISSUE TITLE
Could you please introduce the function of the file ckpt.t7?

### ISSUE THREAD

**Issue by Ocean-ZHY** [mikel-brostrom/Yolov5_DeepSort_Pytorch#99]
Could you please introduce the function of the file ckpt.t7, the training method and the format of the data set?

**Comment by mikel-brostrom** [comment]
**function of the file ckpt.t7**

The association process in Deep Sort is done based on two things: 

1. Mahalanobis distance between predicted Kalman states and newly arrived measurements
2. Appearance descriptor, which is calculated by `ckpt.t7`

In combination, both metrics complement each other by serving  different aspects of the assignment problem. The Mahalonobis distance is suitable when the motion uncertainty is low, but when there is occlusion and/or unaccounted frame skipping  the  Mahalanobis distance is rather useless. Therefore, the idea is to use a visual metric to complement the motion metric. In order to do this an appearance descriptor is calculated for each bounding box detections and are compared to a "gallery" of appearance descriptors, this is particularly useful to recover identities after long-term occlusions or rapid displacements.

**training method**

I would suggest you to go to the original repositories this one is based on for more detailed information about their respective training pipelines.

**format of the data set**

To train the model, first you need download Market1501 dataset or Mars dataset. They are basically comprised of folders with images associated to the same instance object where all the images are of the same size (in the case of Mars for example 128 x 256).

**Comment by Ocean-ZHY** [comment]
Your answer is very useful to me, thank you very much
